upstream backend_api {
    server api:3000 max_fails=3 fail_timeout=30s;
    least_conn;
}

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # ======================
    # React SPA fallback
    # ======================
    location / {
        try_files $uri /index.html;
    }

    # ======================
    # API Proxy
    # ======================
    location /api/ {
        proxy_pass http://backend_api;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location /nginx-health {
        return 200 "nginx is healthy\n";
    }
}