# backend workflow

name: backend CI/CD pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
    
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'frontend/**'

jobs:

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20, 22 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run linter
        working-directory: ./backend
        run: npm run lint

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20, 22 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run unit tests
        working-directory: ./backend
        run: npm run test:unit

  integration-test:
    name: Integration Tests
    needs: [lint, unit-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20, 22 ]

    services:
      postgres:
       image: postgres:15
       env:
        POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
        POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
      options: >-
        --health-cmd "pg_isready -U postgres"
        --health-interval 5s
        --health-timeout 5s
        --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://${{ secrets.TEST_DB_USER }}:${{ secrets.TEST_DB_PASSWORD }}@postgres:5432/${{ secrets.TEST_DB_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run integration tests
        working-directory: ./backend
        run: npm run test:integration      
