# frontend workflow

name: frontend CI/CD pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
    
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'backend/**'

jobs:

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20, 22 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run linter
        working-directory: ./frontend
        run: npm run lint

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20, 22 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run unit tests
        working-directory: ./frontend
        run: npm run test:ci
  

  dependency-scan:
    name: Dependency scan - npm audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20, 22 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run npm audit
        working-directory: ./frontend
        run: npm audit --audit-level=high || true

      - name: Save audit report
        working-directory: ./frontend
        run: npm audit --json > npm-audit.json || true
      
      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report-node-${{ matrix.node-version }}
          path: frontend/npm-audit.json